
language: php
sudo: false
addons:
  apt:
    packages:
    - ldap-utils
    - slapd
    
php:
  - 5.6
  - 7.0

before_script:
  - phpenv config-add travis.php.ini
  - composer install
  - phpenv config-add tests/travis/enable-ldap.ini
  - pear upgrade pear-1.10.1
  - cat tests/ldapconfig.ini.dist | sed s/389/3389/ > tests/ldapconfig.ini
  - mkdir /tmp/slapd
  - slapd -f tests/ldif_data/slapd.conf -h ldap://localhost:3389 &
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=test,dc=com -w test -f tests/ldif_data/base.ldif
  - ldapadd -h localhost:3389 -D cn=admin,dc=test,dc=com -w test -f tests/ldif_data/INITIAL_TESTDATA.ldif

script:
  - ant

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/satooshi/php-coveralls/bin/coveralls -v; fi
  - vendor/bin/security-checker -n security:check

notifications:
  email:
  - andrea.manzi@libero.it
